### ISSUE TITLE
Relation to sisl/CrossEntropyMethod.jl

### ISSUE THREAD

**Issue by xukai92** [mossr/CrossEntropyVariants.jl#1]
Hi! Thanks for this really nice package. 
I wonder how does it related to sisl/CrossEntropyMethod.jl?
Is there a plan to merge them into a single package or so?

**Comment by mossr** [comment]
Glad you like it! The "sisl" version of the code is the official version, mine here is just an old fork.

**Comment by xukai92** [comment]
Cool. I will stay with that sisl version then :)
